URL1 = https://demo.applitools.com/
URL2 = https://www.demoblaze.com/index.html
URL3 = https://www.demoblaze.com/index.html#
URL4 = https://practice.expandtesting.com/dynamic-table
URL5 = https://seleniumbase.io/demo_page
URL6 = https://letcode.in/calendar
D:\\intelij\\AutoBank\\properties\\details.properties